create table Prestamos (PrestamosID int identity(1 , 1),
    PrestamoID varchar(10),
    CantidadCuotas varchar(10),
    Interes varchar(10),
    MontoPrestado varchar(10),
    Meses varchar(10),
    FormaDePago varchar(10),
    Garante varchar(25),
    Desde datetime,
    Hasta datetime,
    MesesgraciasMonatoria varchar(10),
    DiasgraciasMonatoria varchar(10),
	MontoMesesMonatoria varchar(10),
    MontoDiaMonatoria varchar(10)
);